apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: external-secrets-hub-ca
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: all-openshift-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: external-secrets-hub-ca
    kind: Policy
    apiGroup: policy.open-cluster-management.io
