apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - https://github.com/tom-stockwell/gitops-common//hashicorp-vault/overlays/default?ref=main
  - serviceaccount.yml
  - rbac.yml
  - cronjob.yml

configMapGenerator:
  - name: vault-unseal-ansible
    files:
      - files/ansible.cfg
      - files/playbook.yml
      - defaults-main.yml=files/roles/vault_utils/defaults/main.yml
      - tasks-main.yml=files/roles/vault_utils/tasks/main.yml
      - files/roles/vault_utils/tasks/pre_check.yaml
      - files/roles/vault_utils/tasks/push_secrets.yaml
      - files/roles/vault_utils/tasks/vault_init.yaml
      - files/roles/vault_utils/tasks/vault_secrets_init.yaml
      - files/roles/vault_utils/tasks/vault_spokes_init.yaml
      - files/roles/vault_utils/tasks/vault_status.yaml
      - files/roles/vault_utils/tasks/vault_unseal.yaml
      - files/plugins/modules/vault_load_secrets.py
      - files/plugins/filter/parse_acm_secrets.py
      - files/inventory/host_vars/localhost.yml
