---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-unsealer
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: vault-unsealer
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unsealer
subjects:
  - kind: ServiceAccount
    name: vault-unsealer
    namespace: default
