apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        metadata:
          name: vault-unseal
        spec:
          serviceAccountName: vault-unsealer
          initContainers:
            - name: unseal-playbook
              image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
              imagePullPolicy: Always
              workingDir: /runner/project
              env:
                - name: ANSIBLE_CONFIG
                  value: /runner/project/ansible.cfg
              command:
                - timeout
                - '600'
                - ansible-playbook
                - -t
                - vault_init,vault_unseal,vault_secrets_init,vault_spokes_init
                - playbook.yml
              volumeMounts:
                - name: ansible
                  mountPath: /runner/project
          containers:
            - name: done
              image: registry.access.redhat.com/ubi9/ubi-minimal:latest
              imagePullPolicy: Always
              command:
                - 'sh'
                - '-c'
                - 'echo'
                - 'done'
                - '\n'
          volumes:
            - name: ansible
              configMap:
                name: vault-unseal-ansible
                items:
                  - key: ansible.cfg
                    path: ansible.cfg
                  - key: playbook.yml
                    path: playbook.yml
                  - key: defaults-main.yml
                    path: roles/vault_utils/defaults/main.yml
                  - key: tasks-main.yml
                    path: roles/vault_utils/tasks/main.yml
                  - key: tasks-pre_check.yaml
                    path: roles/vault_utils/tasks/pre_check.yaml
                  - key: tasks-push_secrets.yaml
                    path: roles/vault_utils/tasks/push_secrets.yaml
                  - key: tasks-vault_init.yaml
                    path: roles/vault_utils/tasks/vault_init.yaml
                  - key: tasks-vault_secrets_init.yaml
                    path: roles/vault_utils/tasks/vault_secrets_init.yaml
                  - key: tasks-vault_spokes_init.yaml
                    path: roles/vault_utils/tasks/vault_spokes_init.yaml
                  - key: tasks-vault_status.yaml
                    path: roles/vault_utils/tasks/vault_status.yaml
                  - key: tasks-vault_unseal.yaml
                    path: roles/vault_utils/tasks/vault_unseal.yaml
                  - key: plugins-vault_load_secrets.py
                    path: plugins/modules/vault_load_secrets.py
                  - key: inventory-localhost.yml
                    path: inventory/host_vars/localhost.yml
          restartPolicy: Never
