apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault-vault.hub.example.com
      path: secret
      version: v2
      caProvider:
        type: ConfigMap
        name: kube-root-ca.crt
        key: ca.crt
        namespace: external-secrets
      auth:
        kubernetes:
          mountPath: hub
          role: hub-role
          secretRef:
            name: cluster-external-secrets
            namespace: external-secrets
            key: "token"
