apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault-vault.CHANGEME.com
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: hub-ca.crt
        namespace: external-secrets
        key: ca.crt
      auth:
        kubernetes:
          mountPath: hub
          role: hub-role
          secretRef:
            name: cluster-external-secrets
            namespace: external-secrets
            key: "token"
