apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management-policies

resources:
- namespace.yml
- external-secrets/placementbinding.yml
- external-secrets/policy.yml
- placementrule-all-openshift-clusters.yml
