apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management-policies

resources:
- namespace.yml
- placementrule-all-openshift-clusters.yml
- placementrule-managed-clusters.yml
- policy-external-secrets.yml
- policy-openshift-gitops.yml
