---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: vault-unsealer
    namespace: vault
